### ISSUE TITLE
How i can call step.Run or step.Invoke concurrently in goroutines 

### ISSUE THREAD

**Issue by rullyalves** [inngest/inngestgo#47]
Example code inside function that run step.Run / step.Invoke in parallel and collect results

``` go
			var wg sync.WaitGroup

			inputs := []string{"a", "b", "c"}
			inputsLength := len(inputs)

			results := make([]string, inputsLength)
			errs := make([]error, inputsLength)

			for index, item := range inputs {
				wg.Add(1)
				go func(index int, argument string) {
					defer wg.Done()
					run, err := step.Run(ctx, "my-step", func(ctx context.Context) (string, error) {
						// some computation
						// use argument
						return argument, nil
					})
					
					if err != nil {
						errs[index] = err
						return
					}

					results[index] = run
				}(index, item)
			}

			wg.Wait()
			
			/// use results
```

**Comment by rullyalves** [comment]
Looking forward to it

**Comment by goodoldneon** [comment]
@rullyalves, this is the approach we're considering:
https://github.com/inngest/inngestgo/pull/51

Even though waitgroups are super common in Go, we can't support them right now because we use panics to interrupt control flow. This may change in the future if we find a replacement for our panic-based interruption approach

**Comment by rullyalves** [comment]
@goodoldneon Wouldn't it be possible to use recover to recover possible panics?

**Comment by rullyalves** [comment]
@goodoldneon I checked the implementation (https://github.com/inngest/inngestgo/pull/51) and it looks great to me

**Comment by goodoldneon** [comment]
We could get waitgroups working if users were diligent about applying the following recover-and-repanic pattern to every goroutine:
```go
func Fn(ctx context.Context, input inngestgo.Input[any]) (any, error) {
	var recovered any
	wg := sync.WaitGroup{}
	wg.Add(1)

	go func() {
		defer wg.Done()
		defer func() {
			if r := recover(); r != nil {
				// Store panic so we can repanic outside this goroutine
				recovered = r
			}
		}()

		_, _ = step.Run(ctx, "fetch todo", func(ctx context.Context) (int, error) {
			return 1, nil
		})
	}()
	if recovered != nil {
		// Repanic so the SDK's recover logic can run
		panic(recovered)
	}

	return nil, nil
}
```

But we think that pattern hurts readability and is a footgun. That footgun is exacerbated by our intentional panics and the fact that a Go process crashes on unrecovered panics in goroutines

**Comment by rullyalves** [comment]
Would something at that level work ?

```go
type FnStep[T any] struct {
	ID string
	Fn func(ctx context.Context) (T, error)
}

type ResultFn[T any] struct {
	result T
	error
}

func RunStepOnParallel(ctx context.Context, fns []FnStep[any]) []ResultFn[any] {
	var recovered any
	mut := sync.Mutex{}
	wg := sync.WaitGroup{}

	results := make([]ResultFn[any], len(fns))

	for i, fn := range fns {
		wg.Add(1)
		go func(index int, fn FnStep[any], mut *sync.Mutex) {
			defer wg.Done()
			defer func() {
				mut.Lock()
				if r := recover(); r != nil {
					// Store panic so we can repanic outside this goroutine
					recovered = r
				}
				mut.Unlock()
			}()
			result, err := step.Run(ctx, fn.ID, fn.Fn)

			results[index] = ResultFn[any]{result: result, error: err}
		}(i, fn, &mut)
	}

	if recovered != nil {
		// Repanic so the SDK's recover logic can run
		panic(recovered)
	}

	return results
}
```

**Comment by goodoldneon** [comment]
I think we could get your example working, but that's a lot of stuff that users need to remember to do every time. Supporting common concurrency patterns in Go is important to us, but we're afraid that all the extra panic-related stuff cancels out the benefit of common patterns

**Comment by rullyalves** [comment]
I thought about maybe incorporating the function I gave as an example into the ingest sdk, it seems like it would be a relatively simple solution to meet this standard, I will test it in my codebase, but do you think it has promise ?

**Comment by rullyalves** [comment]
So isn't it enough to execute the steps in different goroutines and wait for them? Is it also necessary to find out which steps are parallel and send them to ingest? Why?

**Comment by goodoldneon** [comment]
We never want to execute multiple steps within the same HTTP request since that decreases our "as close to exactly-once execution as we can get" guarantee.

Let's say we execute 2 steps in parallel within the same HTTP request.

## Happy path
We wait until both steps are done and then put their outputs in the response back to the Inngest Server. Great! No issues.

## Unhappy path
Step 1 completes but then step 2 irrecoverably panics. The whole Go process crashes and step 1's output isn't sent back the to Inngest Server. Now the Inngest Server thinks step 1 didn't finish so it tries to run it again. Now we ran the logic in step 1 twice.

**Comment by rullyalves** [comment]
in the worst case, some step would be executed more than once, right?

so the code I posted could work, but there would be this possible case where one of the steps could fail irreparably, right? ok, I think for my use case I can deal with this while there is no official update with this function

**Comment by goodoldneon** [comment]
I don't think it would work now because our control flow interrupt of the first completed step would leave the other steps hanging. Also, Inngest Servers are incapable of handling multiple step outputs in a single HTTP response.

I'll ask the team if they're OK with merging the `group.Parallel` PR to unblock you. I think we can get it in soon

**Comment by rullyalves** [comment]
Thank you, I look forward to hearing from you, if I can help in any way, please let me know.

**Comment by goodoldneon** [comment]
@rullyalves, we released an experimental version of `group.Parallel` in `v0.7.4`. Here's our integration test that gives an idea about how to use it:
https://github.com/inngest/inngestgo/blob/v0.7.4/tests/parallel_test.go#L55-L84

**Comment by rullyalves** [comment]
Thanks for your attention, I will update my workflows with this version of the library and tests, but this should greatly improve the execution time of the steps

**Comment by goodoldneon** [comment]
We don't have a specific limit for parallel steps. They're subject to the overall 1000 step limit for a function run, so you should be able to do 1000 steps in parallel if there are no other steps.

That said, right now our parallel step execution model is kind of inefficient: each parallel step requires 2 HTTP requests. We'll change this in the near future, but for now it's something to consider since it affects your ingress bandwidth

**Comment by rullyalves** [comment]
I made a code, in theory this would be the use ?
I will call the steps in parallel, collect the list of Result, and if there is an error, I return it so that the function tries again and re-executes the steps that resulted in an error?

```go
			rs := group.Parallel(ctx, func(ctx context.Context) (any, error) {
				return step.Run(ctx, "step a", func(ctx context.Context) (any, error) {
					return nil, nil
				})
			}, func(ctx context.Context) (any, error) {
				return step.Invoke[any](ctx, "moderate-texts", step.InvokeOpts{
					FunctionId: "step b",
				})
			})

			anyError := collections.FirstWhereOrNil(rs, func(result group.Result) bool {
				return result.Error != nil
			})

			if anyError != nil {
				return nil, anyError.Error
			}

			classifyTextResult := rs[0].Value
			moderateTextResult := rs[1].Value
```

**Comment by goodoldneon** [comment]
Retries are already handled automatically. A `step.Run` call only returns an error after retries are exhausted.

Note that `step.Invoke`'s retries are the responsibility of the _invoked_ function. In other words, if you invoke a function with 3 retries and it fails, then `step.Invoke` will return an error with no further retries

**Comment by goodoldneon** [comment]
Returning the `step.Run` error won't cause any more retries since the retries already happened.

Try running this function:
```go
inngestgo.CreateFunction(
	inngestgo.FunctionOpts{
		ID:      "my-fn",
		Name:    "my-fn",
		Retries: inngestgo.IntPtr(1),
	},
	inngestgo.EventTrigger("my-event", nil),
	func(ctx context.Context, input inngestgo.Input[any]) (any, error) {
		_, err := step.Run(ctx, "a", func(ctx context.Context) (any, error) {
			fmt.Println("inside step")
			return nil, fmt.Errorf("oh no")
		})
		fmt.Println("after step")
		return nil, err
	},
)
```

Since it's configured for 1 retry, you'll see the following in your terminal:
```
inside step
inside step
after step
```

And then the function will fail. The 2 retries are for the step, which means `step.Run` returns the error after the retry is done

**Comment by rullyalves** [comment]
sorry, English is not my native language, so I may not be expressing myself well, but I wanted to ask if the implementation I put in the code example is correct, I understand that steps by default try again and only return error or success after exhausting the attempts and that the same happens for a function

**Comment by goodoldneon** [comment]
That code is the most common way people use parallel steps: fail the function if at least 1 parallel step errors. The code looks good, except the comment would be:
```go
// check if there is any error, if there is then fail the function
```

The `return nil, anyError.Error` will immediately fail the function because retries have already been exhausted
